enablePinning = true
darkMode = false
keepCentered = true
settingsButton = true
enableBook = true

[newRecipes]
unlockAll = true
enableBounce = false

[instantCraft]
showButton = true

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = false
